### ISSUE TITLE
Maual not in line with v2

### ISSUE THREAD

**Issue by TonisOrmisson** [bashkarev/clickhouse#15]
the manual of v2 refers to `batchInsertFiles()` which does not seem to exist and throws an exception

**Comment by sartor** [comment]
Yes, it was deleted. I need to clean documentation. You can use native [smi2 ](https://github.com/smi2/phpClickHouse) methods instead:
> Parallelizing massive inserts from CSV file
```php
$file_data_names = [
    '/tmp/clickHouseDB_test.1.data',
    '/tmp/clickHouseDB_test.2.data',
    '/tmp/clickHouseDB_test.3.data',
    '/tmp/clickHouseDB_test.4.data',
    '/tmp/clickHouseDB_test.5.data',
];

// insert all files
$stat = $db->insertBatchFiles(
    'summing_url_views',
    $file_data_names,
    ['event_time', 'site_key', 'site_id', 'views', 'v_00', 'v_55']
);
```

**Comment by TonisOrmisson** [comment]
ok thanks!

The suggested way of `$db->insertBatchFiles(yada-yada)` still is not working since the `insertBatchFiles()` method seems to be inherited from `bashkarev\clickhouse\Connection::_client` which is private. Calling `bashkarev\clickhouse\Connection ->insertBatchFiles(yada-yada) ` currently results in:
```Error: Calling unknown method: bashkarev\clickhouse\Connection::insertBatchFiles()```

Anyway, I was just playing around to get familiar and got confused by the manual :)

**Comment by sartor** [comment]
I'll fix it in a few days

**Comment by sartor** [comment]
I've updated readme and added getClient method in Connection
