### ISSUE TITLE
Impossible to set database

### ISSUE THREAD

**Issue by sleptor** [bashkarev/clickhouse#2]
Consider to add 'database' property to Connection or improve DSN syntax similar to regular connections (mysql for example): 'dsn' => 'tcp://localhost:8823;dbname=test'

**Comment by bashkarev** [comment]
@sleptor Thanks a lot for your help.
Read more in [https://github.com/bashkarev/clickhouse#configuration](readme)

**Comment by sleptor** [comment]
perfect! thanks
