### ISSUE TITLE
Sockets vs. Curl

### ISSUE THREAD

**Issue by sleptor** [bashkarev/clickhouse#3]
Which are the points to use "low-level" sockets instead of yii-httpclient for example?
Performance? Could you provide a link to some tests or articles?
Otherwise, it looks like the wheel reinventing :)

**Comment by bashkarev** [comment]
1. Keep-alive support
2. Not demanding to memory
3. Future asynchrony.

The benchmarks will be later, the difference with curl is considerable.

**Comment by sleptor** [comment]
1. "Keep-alive" what does it means in the context of the Clickhouse? does Clickhouse support keep-alive http option?
2. probably yes
3. curl has async request with the options curl_multi_*

In my opinion, sockets are just a transport. It's should be separated from the main functionality.
consider making separate package either use 3rd party or maybe create an additional transport for Guzzle for example

**Comment by bashkarev** [comment]
1. Yes `http`.

I'll think about the separation of transport, but at the moment I do not see an efficient way.

**Comment by sartor** [comment]
I will try to separate current connection code from other logic. For now i have problems with sending large data. Sometimes reading or writing is just stop in infinitive loop. I've tried to use https://github.com/smi2/phpClickHouse and it work well with same amounts of data. May be we can use its transport and connection layers?

**Comment by sartor** [comment]
I've wrote alpha version of smi2 driver (29e6f78bc091292e0247c67eeb0bf5d206d84ac0). The only thing I dropped for now is InsertFiles class because of smi2 driver has already have same functionality

**Comment by rezikovka** [comment]
@bashkarev Using socket i have some troubles. Time to time in bashkarev\clickhouse\Parser at line 47 i get an infinite loop. It happens during connection to remote server. Unfortunately it makes imposible to using this library in my current project. So an idea of separation looks realy usefull :+1:

**Comment by bashkarev** [comment]
try version 2, it is based on smi2/phpclickhouse

**Comment by lizhichao** [comment]
Clickhouse will generate a part every time it is written. Use tcp to stream test writes. Multiple block data generates a part. When the number of writes each time is less than 1000, this stream test write is much faster than complete writes and uses very little memory.
like this
```php

$t1 = microtime(true);
$ck = new \OneCk\Client('tcp://192.168.31.216:9091');
$ck->query('DROP TABLE IF EXISTS t7');
$table                = [
    'CREATE TABLE t7 (',
    '`id` UInt32,',
    '`f2` Nullable(Int32),',
    '`f5` UInt16,',
    '`f15` String',
    ') ENGINE = MergeTree() ORDER BY id SETTINGS index_granularity = 8192'
];
$ck->query(implode("\n", $table));

$ck->writeStart('t7',['id','f2','f5','f15']);
for ($i = 0; $i < 1000; $i++) {
    $da = [];
    for ($j = 0; $j < 1000; $j++) {
        $da[] = [
            'id' => mt_rand(1,1000000),
            'f2' => mt_rand(-1000000,1000000),
            'f5' => mt_rand(1,10000),
            'f15' => md5(mt_rand(1,10000))
        ];
    }
    $ck->writeBlock($da);
}

$ck->writeEnd();

echo microtime(true) - $t1;


```
