### ISSUE TITLE
Changed column name in ClickHouse 1.1.54237+

### ISSUE THREAD

**Issue by MysteryDragon** [bashkarev/clickhouse#4]
If I get it correctly, starting from ClickHouse 1.1.54237 in `system.columns` `default_type` was renamed to `default_kind`, so it lead to some mistakes, for example [here](https://github.com/bashkarev/clickhouse/blob/313aa5d730c558e40bf6437bf68b1dbad85bba5b/Schema.php#L85).

**Comment by MysteryDragon** [comment]
https://github.com/yandex/ClickHouse/commit/8d570e2768b9bbdc0e26571943df65b94ee45f6f

**Comment by bashkarev** [comment]
Fixed, thanks a lot.
